// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEaQmPY4V3IJ2_zKhtEN3M4UjcUYIpkLA',
    appId: '1:984424053023:web:916927220dd3f2e3eed82a',
    messagingSenderId: '984424053023',
    projectId: 'urbanerafashion-428e7',
    authDomain: 'urbanerafashion-428e7.firebaseapp.com',
    storageBucket: 'urbanerafashion-428e7.appspot.com',
    measurementId: 'G-GWSBLR5L9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcaQwnL_n8gbRJMfYIvbw6idXokrY-bkg',
    appId: '1:984424053023:android:673c57a1ebc6c96beed82a',
    messagingSenderId: '984424053023',
    projectId: 'urbanerafashion-428e7',
    storageBucket: 'urbanerafashion-428e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybOPIKcXVXkAlpDsYh0GBnopj5709QRI',
    appId: '1:984424053023:ios:f9855b2c217ffe43eed82a',
    messagingSenderId: '984424053023',
    projectId: 'urbanerafashion-428e7',
    storageBucket: 'urbanerafashion-428e7.appspot.com',
    iosBundleId: 'com.example.shoppersEcommerceFlutterUiKit',
  );
}
